module.exports = {
  ORDER_STATUS: {
    PENDING_PAYMENT: 'PENDING_PAYMENT',
    PAYMENT_PROCESSING: 'PAYMENT_PROCESSING',
    PAID: 'PAID',
    PAYMENT_FAILED: 'PAYMENT_FAILED',
    CANCELLED: 'CANCELLED'
  }
};
