module.exports = {
  RABBITMQ: {
    PAYMENT_PROCESSING_QUEUE: 'payment-processing-queue'
  },
  PAYMENT_STATUS: {
    PENDING: 'PENDING',
    PROCESSING: 'PROCESSING',
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED'
  },
  ORDER_STATUS: {
    PENDING_PAYMENT: 'PENDING_PAYMENT',
    PAYMENT_PROCESSING: 'PAYMENT_PROCESSING'
  }
};
